/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VidaFinanceiraRouteImport } from './routes/vida-financeira'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as NovoRegistroRouteImport } from './routes/novo-registro'
import { Route as NovoPlantaoRouteImport } from './routes/novo-plantao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LancarPlantoesRouteImport } from './routes/lancar-plantoes'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as FuturoRouteImport } from './routes/futuro'
import { Route as FechamentoRouteImport } from './routes/fechamento'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContadorRouteImport } from './routes/contador'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as Auditoria2026RouteImport } from './routes/auditoria-2026'
import { Route as IndexRouteImport } from './routes/index'

const VidaFinanceiraRoute = VidaFinanceiraRouteImport.update({
  id: '/vida-financeira',
  path: '/vida-financeira',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRegistroRoute = NovoRegistroRouteImport.update({
  id: '/novo-registro',
  path: '/novo-registro',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoPlantaoRoute = NovoPlantaoRouteImport.update({
  id: '/novo-plantao',
  path: '/novo-plantao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LancarPlantoesRoute = LancarPlantoesRouteImport.update({
  id: '/lancar-plantoes',
  path: '/lancar-plantoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturoRoute = FuturoRouteImport.update({
  id: '/futuro',
  path: '/futuro',
  getParentRoute: () => rootRouteImport,
} as any)
const FechamentoRoute = FechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContadorRoute = ContadorRouteImport.update({
  id: '/contador',
  path: '/contador',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const Auditoria2026Route = Auditoria2026RouteImport.update({
  id: '/auditoria-2026',
  path: '/auditoria-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria-2026': typeof Auditoria2026Route
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/contador': typeof ContadorRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/empresa': typeof EmpresaRoute
  '/fechamento': typeof FechamentoRoute
  '/futuro': typeof FuturoRoute
  '/gestao': typeof GestaoRoute
  '/lancar-plantoes': typeof LancarPlantoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/novo-plantao': typeof NovoPlantaoRoute
  '/novo-registro': typeof NovoRegistroRoute
  '/patrimonio': typeof PatrimonioRoute
  '/planos': typeof PlanosRoute
  '/vida-financeira': typeof VidaFinanceiraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria-2026': typeof Auditoria2026Route
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/contador': typeof ContadorRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/empresa': typeof EmpresaRoute
  '/fechamento': typeof FechamentoRoute
  '/futuro': typeof FuturoRoute
  '/gestao': typeof GestaoRoute
  '/lancar-plantoes': typeof LancarPlantoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/novo-plantao': typeof NovoPlantaoRoute
  '/novo-registro': typeof NovoRegistroRoute
  '/patrimonio': typeof PatrimonioRoute
  '/planos': typeof PlanosRoute
  '/vida-financeira': typeof VidaFinanceiraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria-2026': typeof Auditoria2026Route
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/contador': typeof ContadorRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/empresa': typeof EmpresaRoute
  '/fechamento': typeof FechamentoRoute
  '/futuro': typeof FuturoRoute
  '/gestao': typeof GestaoRoute
  '/lancar-plantoes': typeof LancarPlantoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/novo-plantao': typeof NovoPlantaoRoute
  '/novo-registro': typeof NovoRegistroRoute
  '/patrimonio': typeof PatrimonioRoute
  '/planos': typeof PlanosRoute
  '/vida-financeira': typeof VidaFinanceiraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria-2026'
    | '/caixa'
    | '/calendario'
    | '/contador'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/fechamento'
    | '/futuro'
    | '/gestao'
    | '/lancar-plantoes'
    | '/landing'
    | '/login'
    | '/novo-plantao'
    | '/novo-registro'
    | '/patrimonio'
    | '/planos'
    | '/vida-financeira'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria-2026'
    | '/caixa'
    | '/calendario'
    | '/contador'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/fechamento'
    | '/futuro'
    | '/gestao'
    | '/lancar-plantoes'
    | '/landing'
    | '/login'
    | '/novo-plantao'
    | '/novo-registro'
    | '/patrimonio'
    | '/planos'
    | '/vida-financeira'
  id:
    | '__root__'
    | '/'
    | '/auditoria-2026'
    | '/caixa'
    | '/calendario'
    | '/contador'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/fechamento'
    | '/futuro'
    | '/gestao'
    | '/lancar-plantoes'
    | '/landing'
    | '/login'
    | '/novo-plantao'
    | '/novo-registro'
    | '/patrimonio'
    | '/planos'
    | '/vida-financeira'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Auditoria2026Route: typeof Auditoria2026Route
  CaixaRoute: typeof CaixaRoute
  CalendarioRoute: typeof CalendarioRoute
  ContadorRoute: typeof ContadorRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosRoute: typeof DocumentosRoute
  EmpresaRoute: typeof EmpresaRoute
  FechamentoRoute: typeof FechamentoRoute
  FuturoRoute: typeof FuturoRoute
  GestaoRoute: typeof GestaoRoute
  LancarPlantoesRoute: typeof LancarPlantoesRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  NovoPlantaoRoute: typeof NovoPlantaoRoute
  NovoRegistroRoute: typeof NovoRegistroRoute
  PatrimonioRoute: typeof PatrimonioRoute
  PlanosRoute: typeof PlanosRoute
  VidaFinanceiraRoute: typeof VidaFinanceiraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vida-financeira': {
      id: '/vida-financeira'
      path: '/vida-financeira'
      fullPath: '/vida-financeira'
      preLoaderRoute: typeof VidaFinanceiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-registro': {
      id: '/novo-registro'
      path: '/novo-registro'
      fullPath: '/novo-registro'
      preLoaderRoute: typeof NovoRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-plantao': {
      id: '/novo-plantao'
      path: '/novo-plantao'
      fullPath: '/novo-plantao'
      preLoaderRoute: typeof NovoPlantaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancar-plantoes': {
      id: '/lancar-plantoes'
      path: '/lancar-plantoes'
      fullPath: '/lancar-plantoes'
      preLoaderRoute: typeof LancarPlantoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro': {
      id: '/futuro'
      path: '/futuro'
      fullPath: '/futuro'
      preLoaderRoute: typeof FuturoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fechamento': {
      id: '/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof FechamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contador': {
      id: '/contador'
      path: '/contador'
      fullPath: '/contador'
      preLoaderRoute: typeof ContadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria-2026': {
      id: '/auditoria-2026'
      path: '/auditoria-2026'
      fullPath: '/auditoria-2026'
      preLoaderRoute: typeof Auditoria2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Auditoria2026Route: Auditoria2026Route,
  CaixaRoute: CaixaRoute,
  CalendarioRoute: CalendarioRoute,
  ContadorRoute: ContadorRoute,
  DashboardRoute: DashboardRoute,
  DocumentosRoute: DocumentosRoute,
  EmpresaRoute: EmpresaRoute,
  FechamentoRoute: FechamentoRoute,
  FuturoRoute: FuturoRoute,
  GestaoRoute: GestaoRoute,
  LancarPlantoesRoute: LancarPlantoesRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  NovoPlantaoRoute: NovoPlantaoRoute,
  NovoRegistroRoute: NovoRegistroRoute,
  PatrimonioRoute: PatrimonioRoute,
  PlanosRoute: PlanosRoute,
  VidaFinanceiraRoute: VidaFinanceiraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
