/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as NovoRegistroRouteImport } from './routes/novo-registro'
import { Route as NovoPlantaoRouteImport } from './routes/novo-plantao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as FuturoRouteImport } from './routes/futuro'
import { Route as FechamentoRouteImport } from './routes/fechamento'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as IndexRouteImport } from './routes/index'

const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRegistroRoute = NovoRegistroRouteImport.update({
  id: '/novo-registro',
  path: '/novo-registro',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoPlantaoRoute = NovoPlantaoRouteImport.update({
  id: '/novo-plantao',
  path: '/novo-plantao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturoRoute = FuturoRouteImport.update({
  id: '/futuro',
  path: '/futuro',
  getParentRoute: () => rootRouteImport,
} as any)
const FechamentoRoute = FechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/fechamento': typeof FechamentoRoute
  '/futuro': typeof FuturoRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/novo-plantao': typeof NovoPlantaoRoute
  '/novo-registro': typeof NovoRegistroRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/fechamento': typeof FechamentoRoute
  '/futuro': typeof FuturoRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/novo-plantao': typeof NovoPlantaoRoute
  '/novo-registro': typeof NovoRegistroRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/calendario': typeof CalendarioRoute
  '/fechamento': typeof FechamentoRoute
  '/futuro': typeof FuturoRoute
  '/gestao': typeof GestaoRoute
  '/login': typeof LoginRoute
  '/novo-plantao': typeof NovoPlantaoRoute
  '/novo-registro': typeof NovoRegistroRoute
  '/patrimonio': typeof PatrimonioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caixa'
    | '/calendario'
    | '/fechamento'
    | '/futuro'
    | '/gestao'
    | '/login'
    | '/novo-plantao'
    | '/novo-registro'
    | '/patrimonio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caixa'
    | '/calendario'
    | '/fechamento'
    | '/futuro'
    | '/gestao'
    | '/login'
    | '/novo-plantao'
    | '/novo-registro'
    | '/patrimonio'
  id:
    | '__root__'
    | '/'
    | '/caixa'
    | '/calendario'
    | '/fechamento'
    | '/futuro'
    | '/gestao'
    | '/login'
    | '/novo-plantao'
    | '/novo-registro'
    | '/patrimonio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaixaRoute: typeof CaixaRoute
  CalendarioRoute: typeof CalendarioRoute
  FechamentoRoute: typeof FechamentoRoute
  FuturoRoute: typeof FuturoRoute
  GestaoRoute: typeof GestaoRoute
  LoginRoute: typeof LoginRoute
  NovoPlantaoRoute: typeof NovoPlantaoRoute
  NovoRegistroRoute: typeof NovoRegistroRoute
  PatrimonioRoute: typeof PatrimonioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-registro': {
      id: '/novo-registro'
      path: '/novo-registro'
      fullPath: '/novo-registro'
      preLoaderRoute: typeof NovoRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-plantao': {
      id: '/novo-plantao'
      path: '/novo-plantao'
      fullPath: '/novo-plantao'
      preLoaderRoute: typeof NovoPlantaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro': {
      id: '/futuro'
      path: '/futuro'
      fullPath: '/futuro'
      preLoaderRoute: typeof FuturoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fechamento': {
      id: '/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof FechamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaixaRoute: CaixaRoute,
  CalendarioRoute: CalendarioRoute,
  FechamentoRoute: FechamentoRoute,
  FuturoRoute: FuturoRoute,
  GestaoRoute: GestaoRoute,
  LoginRoute: LoginRoute,
  NovoPlantaoRoute: NovoPlantaoRoute,
  NovoRegistroRoute: NovoRegistroRoute,
  PatrimonioRoute: PatrimonioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
